-- AlterTable
ALTER TABLE "Listing" ALTER COLUMN "images" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "features" SET DEFAULT ARRAY[]::TEXT[],
ALTER COLUMN "bathrooms" SET DEFAULT 0,
ALTER COLUMN "bathrooms" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "bedrooms" SET DEFAULT 0,
ALTER COLUMN "bedrooms" SET DATA TYPE DOUBLE PRECISION;
