/** Curated IANA zones for the listing form; server still validates any future free-text expansion. */
export const PROPERTY_IANA_TIMEZONES: { value: string; label: string }[] = [
  { value: "UTC", label: "UTC" },
  { value: "America/New_York", label: "US — Eastern (New York)" },
  { value: "America/Chicago", label: "US — Central (Chicago)" },
  { value: "America/Denver", label: "US — Mountain (Denver)" },
  { value: "America/Los_Angeles", label: "US — Pacific (Los Angeles)" },
  { value: "America/Phoenix", label: "US — Arizona (Phoenix)" },
  { value: "America/Anchorage", label: "US — Alaska (Anchorage)" },
  { value: "Pacific/Honolulu", label: "US — Hawaii (Honolulu)" },
  { value: "America/Toronto", label: "Canada — Eastern (Toronto)" },
  { value: "America/Vancouver", label: "Canada — Pacific (Vancouver)" },
  { value: "Europe/London", label: "UK (London)" },
  { value: "Europe/Paris", label: "France (Paris)" },
  { value: "Europe/Berlin", label: "Germany (Berlin)" },
  { value: "Europe/Madrid", label: "Spain (Madrid)" },
  { value: "Europe/Rome", label: "Italy (Rome)" },
  { value: "Europe/Amsterdam", label: "Netherlands (Amsterdam)" },
  { value: "Europe/Zurich", label: "Switzerland (Zurich)" },
  { value: "Asia/Jerusalem", label: "Israel (Jerusalem)" },
  { value: "Asia/Dubai", label: "UAE (Dubai)" },
  { value: "Asia/Singapore", label: "Singapore" },
  { value: "Asia/Tokyo", label: "Japan (Tokyo)" },
  { value: "Australia/Sydney", label: "Australia (Sydney)" },
  { value: "Pacific/Auckland", label: "New Zealand (Auckland)" },
];
